### ISSUE TITLE
Error:TASK [foreman : rake create foreman database]

### ISSUE THREAD

**Issue by navindharman** [adfinis-sygroup/foreman-ansible#14]
```
fatal: [192.168.0.19]: FAILED! => {"changed": true, "cmd": ["/usr/sbin/foreman-rake", "db:migrate"], "delta": "0:00:0
3.901860", "end": "2017-03-16 21:10:19.692102", "failed": true, "rc": 1, "start": "2017-03-16 21:10:15.790242", "stde
rr": "rake aborted!\nActiveRecord::RecordInvalid: Validation failed: Value is invalid\n/opt/rh/sclo-ror42/root/usr/sh
are/gems/gems/activerecord-4.2.5.1/lib/active_record/validations.rb:79:in `raise_record_invalid'\n/opt/rh/sclo-ror42/
root/usr/share/gems/gems/activerecord-4.2.5.1/lib/active_record/validations.rb:43:in `save!'\n/opt/rh/sclo-ror42/root
/usr/share/gems/gems/activerecord-4.2.5.1/lib/active_record/attribute_methods/dirty.rb:29:in `save!'\n/opt/rh/sclo-ro
r42/root/usr/share/gems/gems/activerecord-4.2.5.1/lib/active_record/transactions.rb:291:in `block in save!'\n/opt/rh/
sclo-ror42/root/usr/share/gems/gems/activerecord-4.2.5.1/lib/active_record/transactions.rb:351:in `block in with_tran
saction_returning_status'\n/opt/rh/sclo-ror42/root/usr/share/gems/gems/activerecord-4.2.5.1/lib/active_record/connect
ion_adapters/abstract/database_statements.rb:211:in `transaction'\n/opt/rh/sclo-ror42/root/usr/share/gems/gems/active
record-4.2.5.1/lib/active_record/transactions.rb:220:in `transaction'\n/opt/rh/sclo-ror42/root/usr/share/gems/gems/ac
tiverecord-4.2.5.1/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'\n/opt/rh/sclo-ror42/r
oot/usr/share/gems/gems/activerecord-4.2.5.1/lib/active_record/transactions.rb:291:in `save!'\n/opt/rh/sclo-ror42/roo
t/usr/share/gems/gems/activerecord-4.2.5.1/lib/active_record/persistence.rb:51:in `create!'\n/usr/share/foreman/app/m
odels/setting.rb:201:in `create!'\n/usr/share/foreman/app/models/setting/email.rb:29:in `block (2 levels) in load_def
aults'\n/usr/share/foreman/app/models/setting/email.rb:29:in `each'\n/usr/share/foreman/app/models/setting/email.rb:2
9:in `block in load_defaults'\n/opt/rh/sclo-ror42/root/usr/share/gems/gems/activerecord-4.2.5.1/lib/active_record/con
nection_adapters/abstract/database_statements.rb:213:in `block in transaction'\n/opt/rh/sclo-ror42/root/usr/share/gem
s/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transact
ion'\n/opt/rh/sclo-ror42/root/usr/share/gems/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract
/database_statements.rb:213:in `transaction'\n/opt/rh/sclo-ror42/root/usr/share/gems/gems/activerecord-4.2.5.1/lib/ac
tive_record/transactions.rb:220:in `transaction'\n/usr/share/foreman/app/models/setting/email.rb:13:in `load_defaults
'\n/usr/share/foreman/config/initializers/foreman.rb:25:in `each'\n/usr/share/foreman/config/initializers/foreman.rb:
25:in `<top (required)>'\n/opt/rh/sclo-ror42/root/usr/share/gems/gems/activesupport-4.2.5.1/lib/active_support/depend
encies.rb:268:in `load'\n/opt/rh/sclo-ror42/root/usr/share/gems/gems/activesupport-4.2.5.1/lib/active_support/depende
ncies.rb:268:in `block in load'\n/opt/rh/sclo-ror42/root/usr/share/gems/gems/activesupport-4.2.5.1/lib/active_support
/dependencies.rb:240:in `load_dependency'\n/opt/rh/sclo-ror42/root/usr/share/gems/gems/activesupport-4.2.5.1/lib/acti
ve_support/dependencies.rb:268:in `load'\n/opt/rh/sclo-ror42/root/usr/share/gems/gems/railties-4.2.5.1/lib/rails/engi
ne.rb:652:in `block in load_config_initializer'\n/opt/rh/sclo-ror42/root/usr/share/gems/gems/activesupport-4.2.5.1/li
b/active_support/notifications.rb:166:in `instrument'\n/opt/rh/sclo-ror42/root/usr/share/gems/gems/railties-4.2.5.1/l
ib/rails/engine.rb:651:in `load_config_initializer'\n/opt/rh/sclo-ror42/root/usr/share/gems/gems/railties-4.2.5.1/lib
/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'\n/opt/rh/sclo-ror42/root/usr/share/gems/gems/railties-4.
2.5.1/lib/rails/engine.rb:615:in `each'\n/opt/rh/sclo-ror42/root/usr/share/gems/gems/railties-4.2.5.1/lib/rails/engin
e.rb:615:in `block in <class:Engine>'\n/opt/rh/sclo-ror42/root/usr/share/gems/gems/railties-4.2.5.1/lib/rails/initial
izable.rb:30:in `instance_exec'\n/opt/rh/sclo-ror42/root/usr/share/gems/gems/railties-4.2.5.1/lib/rails/initializable
.rb:30:in `run'\n/opt/rh/sclo-ror42/root/usr/share/gems/gems/railties-4.2.5.1/lib/rails/initializable.rb:55:in `block
 in run_initializers'\n/opt/rh/sclo-ror42/root/usr/share/gems/gems/railties-4.2.5.1/lib/rails/initializable.rb:44:in 
`each'\n/opt/rh/sclo-ror42/root/usr/share/gems/gems/railties-4.2.5.1/lib/rails/initializable.rb:44:in `tsort_each_chi
ld'\n/opt/rh/sclo-ror42/root/usr/share/gems/gems/railties-4.2.5.1/lib/rails/initializable.rb:54:in `run_initializers'
\n/opt/rh/sclo-ror42/root/usr/share/gems/gems/railties-4.2.5.1/lib/rails/application.rb:352:in `initialize!'\n/opt/rh
/sclo-ror42/root/usr/share/gems/gems/railties-4.2.5.1/lib/rails/railtie.rb:194:in `public_send'\n/opt/rh/sclo-ror42/r
oot/usr/share/gems/gems/railties-4.2.5.1/lib/rails/railtie.rb:194:in `method_missing'\n/usr/share/foreman/config/envi
ronment.rb:5:in `<top (required)>'\n/opt/rh/sclo-ror42/root/usr/share/gems/gems/activesupport-4.2.5.1/lib/active_supp
ort/dependencies.rb:274:in `block in require'\n/opt/rh/sclo-ror42/root/usr/share/gems/gems/activesupport-4.2.5.1/lib/
active_support/dependencies.rb:240:in `load_dependency'\n/opt/rh/sclo-ror42/root/usr/share/gems/gems/activesupport-4.
2.5.1/lib/active_support/dependencies.rb:274:in `require'\n/opt/rh/sclo-ror42/root/usr/share/gems/gems/railties-4.2.5
.1/lib/rails/application.rb:328:in `require_environment!'\n/opt/rh/sclo-ror42/root/usr/share/gems/gems/railties-4.2.5
.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'\nTasks: TOP => db:migrate => environment\n(See full tr
ace by running task with --trace)", "stdout": "Apipie cache enabled but not present yet. Run apipie:cache rake task t
o speed up API calls.", "stdout_lines": ["Apipie cache enabled but not present yet. Run apipie:cache rake task to spe
ed up API calls."], "warnings": []}
```

**Comment by karras** [comment]
Could you please provide some additional information? 
* Foreman version
* Is this a new installation?
* Distribution and version? (I guess CentOS)

I think we can get more information by running the migration task manually to see where exactly it fails. Try to run `foreman-rake db:migrate`.

**Comment by karras** [comment]
```
fatal: [192.168.0.19]: FAILED! => {"changed": true, "cmd": ["/usr/sbin/foreman-rake", "db:migrate"]

ActiveRecord::RecordInvalid: Validation failed: Value is invalid
[...]

/opt/rh/sclo-ror42/root/usr/share/gems/gems/railties-4.2.5.1/lib/rails/application.rb:328:in `require_environment!'
Tasks: TOP => db:migrate => environment
```

**Comment by GR360RY** [comment]
@navindharman , there is a chance that you get this error due to missing FQDN.
Please verify by running the below command on the target host:

```
vagrant@foreman:~$ ruby -rfacter -e 'puts Facter.value(:domain).inspect'
nil
``` 
If you get `nil` in response, that means you have to setup domain name for your host.
The error is confirmed both on CentOS7 and Ubuntu 14.04.

Case reference [link](http://projects.theforeman.org/issues/15699)

The exact error message on Ubuntu 14.04 is below ( \n replaced with new line )
```
rake aborted!
ActiveRecord::RecordInvalid: Validation failed: Value is invalid
/usr/share/foreman/vendor/ruby/2.0.0/gems/activerecord-4.2.7.1/lib/active_record/validations.rb:79:in `raise_record_invalid'
/usr/share/foreman/vendor/ruby/2.0.0/gems/activerecord-4.2.7.1/lib/active_record/validations.rb:43:in `save!'
/usr/share/foreman/vendor/ruby/2.0.0/gems/activerecord-4.2.7.1/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
/usr/share/foreman/vendor/ruby/2.0.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:291:in `block in save!'
/usr/share/foreman/vendor/ruby/2.0.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
/usr/share/foreman/vendor/ruby/2.0.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
/usr/share/foreman/vendor/ruby/2.0.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:220:in `transaction'
/usr/share/foreman/vendor/ruby/2.0.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
/usr/share/foreman/vendor/ruby/2.0.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:291:in `save!'
/usr/share/foreman/vendor/ruby/2.0.0/gems/activerecord-4.2.7.1/lib/active_record/persistence.rb:51:in `create!'
/usr/share/foreman/app/models/setting.rb:201:in `create!'
/usr/share/foreman/app/models/setting/email.rb:29:in `block (2 levels) in load_defaults'
/usr/share/foreman/app/models/setting/email.rb:29:in `each'
/usr/share/foreman/app/models/setting/email.rb:29:in `block in load_defaults'
/usr/share/foreman/vendor/ruby/2.0.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/usr/share/foreman/vendor/ruby/2.0.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/usr/share/foreman/vendor/ruby/2.0.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/usr/share/foreman/vendor/ruby/2.0.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:220:in `transaction'
/usr/share/foreman/app/models/setting/email.rb:13:in `load_defaults'
/usr/share/foreman/config/initializers/foreman.rb:25:in `each'
/usr/share/foreman/config/initializers/foreman.rb:25:in `<top (required)>'
/usr/share/foreman/vendor/ruby/2.0.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
/usr/share/foreman/vendor/ruby/2.0.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
/usr/share/foreman/vendor/ruby/2.0.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/share/foreman/vendor/ruby/2.0.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
/usr/share/foreman/vendor/ruby/2.0.0/gems/railties-4.2.7.1/lib/rails/engine.rb:652:in `block in load_config_initializer'
/usr/share/foreman/vendor/ruby/2.0.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
/usr/share/foreman/vendor/ruby/2.0.0/gems/railties-4.2.7.1/lib/rails/engine.rb:651:in `load_config_initializer'
/usr/share/foreman/vendor/ruby/2.0.0/gems/railties-4.2.7.1/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/usr/share/foreman/vendor/ruby/2.0.0/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `each'
/usr/share/foreman/vendor/ruby/2.0.0/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `block in <class:Engine>'
/usr/share/foreman/vendor/ruby/2.0.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
/usr/share/foreman/vendor/ruby/2.0.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
/usr/share/foreman/vendor/ruby/2.0.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/share/foreman/vendor/ruby/2.0.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
/usr/share/foreman/vendor/ruby/2.0.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'
/usr/share/foreman/vendor/ruby/2.0.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
/usr/share/foreman/vendor/ruby/2.0.0/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
/usr/share/foreman/vendor/ruby/2.0.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `public_send'
/usr/share/foreman/vendor/ruby/2.0.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `method_missing'
/usr/share/foreman/config/environment.rb:5:in `<top (required)>'
/usr/share/foreman/vendor/ruby/2.0.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/share/foreman/vendor/ruby/2.0.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/usr/share/foreman/vendor/ruby/2.0.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/share/foreman/vendor/ruby/2.0.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/share/foreman/vendor/ruby/2.0.0/gems/railties-4.2.7.1/lib/rails/application.rb:328:in `require_environment!'
/usr/share/foreman/vendor/ruby/2.0.0/gems/railties-4.2.7.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/usr/share/foreman/vendor/ruby/2.0.0/gems/activerecord-4.2.7.1/lib/active_record/railties/databases.rake:182:in `block (2 levels) in <top (required)>'
/usr/bin/rake2.0:37:in `<main>'
Tasks: TOP => db:abort_if_pending_migrations => environment
(See full trace by running task with --trace)", "stderr_lines": ["rake aborted!", "ActiveRecord::RecordInvalid: Validation failed: Value is invalid", "/usr/share/foreman/vendor/ruby/2.0.0/gems/activerecord-4.2.7.1/lib/active_record/validations.rb:79:in `raise_record_invalid'", "/usr/share/foreman/vendor/ruby/2.0.0/gems/activerecord-4.2.7.1/lib/active_record/validations.rb:43:in `save!'", "/usr/share/foreman/vendor/ruby/2.0.0/gems/activerecord-4.2.7.1/lib/active_record/attribute_methods/dirty.rb:29:in `save!'", "/usr/share/foreman/vendor/ruby/2.0.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:291:in `block in save!'", "/usr/share/foreman/vendor/ruby/2.0.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'", "/usr/share/foreman/vendor/ruby/2.0.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'", "/usr/share/foreman/vendor/ruby/2.0.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:220:in `transaction'", "/usr/share/foreman/vendor/ruby/2.0.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'", "/usr/share/foreman/vendor/ruby/2.0.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:291:in `save!'", "/usr/share/foreman/vendor/ruby/2.0.0/gems/activerecord-4.2.7.1/lib/active_record/persistence.rb:51:in `create!'", "/usr/share/foreman/app/models/setting.rb:201:in `create!'", "/usr/share/foreman/app/models/setting/email.rb:29:in `block (2 levels) in load_defaults'", "/usr/share/foreman/app/models/setting/email.rb:29:in `each'", "/usr/share/foreman/app/models/setting/email.rb:29:in `block in load_defaults'", "/usr/share/foreman/vendor/ruby/2.0.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'", "/usr/share/foreman/vendor/ruby/2.0.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'", "/usr/share/foreman/vendor/ruby/2.0.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'", "/usr/share/foreman/vendor/ruby/2.0.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:220:in `transaction'", "/usr/share/foreman/app/models/setting/email.rb:13:in `load_defaults'", "/usr/share/foreman/config/initializers/foreman.rb:25:in `each'", "/usr/share/foreman/config/initializers/foreman.rb:25:in `<top (required)>'", "/usr/share/foreman/vendor/ruby/2.0.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'", "/usr/share/foreman/vendor/ruby/2.0.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'", "/usr/share/foreman/vendor/ruby/2.0.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'", "/usr/share/foreman/vendor/ruby/2.0.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'", "/usr/share/foreman/vendor/ruby/2.0.0/gems/railties-4.2.7.1/lib/rails/engine.rb:652:in `block in load_config_initializer'", "/usr/share/foreman/vendor/ruby/2.0.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'", "/usr/share/foreman/vendor/ruby/2.0.0/gems/railties-4.2.7.1/lib/rails/engine.rb:651:in `load_config_initializer'", "/usr/share/foreman/vendor/ruby/2.0.0/gems/railties-4.2.7.1/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'", "/usr/share/foreman/vendor/ruby/2.0.0/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `each'", "/usr/share/foreman/vendor/ruby/2.0.0/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `block in <class:Engine>'", "/usr/share/foreman/vendor/ruby/2.0.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'", "/usr/share/foreman/vendor/ruby/2.0.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'", "/usr/share/foreman/vendor/ruby/2.0.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'", "/usr/share/foreman/vendor/ruby/2.0.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'", "/usr/share/foreman/vendor/ruby/2.0.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'", "/usr/share/foreman/vendor/ruby/2.0.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'", "/usr/share/foreman/vendor/ruby/2.0.0/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'", "/usr/share/foreman/vendor/ruby/2.0.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `public_send'", "/usr/share/foreman/vendor/ruby/2.0.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `method_missing'", "/usr/share/foreman/config/environment.rb:5:in `<top (required)>'", "/usr/share/foreman/vendor/ruby/2.0.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'", "/usr/share/foreman/vendor/ruby/2.0.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'", "/usr/share/foreman/vendor/ruby/2.0.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'", "/usr/share/foreman/vendor/ruby/2.0.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'", "/usr/share/foreman/vendor/ruby/2.0.0/gems/railties-4.2.7.1/lib/rails/application.rb:328:in `require_environment!'", "/usr/share/foreman/vendor/ruby/2.0.0/gems/railties-4.2.7.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'", "/usr/share/foreman/vendor/ruby/2.0.0/gems/activerecord-4.2.7.1/lib/active_record/railties/databases.rake:182:in `block (2 levels) in <top (required)>'", "/usr/bin/rake2.0:37:in `<main>'", "Tasks: TOP => db:abort_if_pending_migrations => environment", "(See full trace by running task with --trace)"], "stdout": "Apipie cache enabled but not present yet. Run apipie:cache rake task to speed up API calls.
Successfully decrypted field for Setting::General fix_db_cache
Successfully decrypted field for Setting::General fix_db_cache
Successfully decrypted field for Setting::General fix_db_cache", "stdout_lines": ["Apipie cache enabled but not present yet. Run apipie:cache rake task to speed up API calls.", "Successfully decrypted field for Setting::General fix_db_cache", "Successfully decrypted field for Setting::General fix_db_cache", "Successfully decrypted field for Setting::General fix_db_cache
```

@karras , I think you can close the case.

**Comment by karras** [comment]
Awesome, thanks @GR360RY!
